### ISSUE TITLE
After update of AlphaESS infrastructure integration is no longer working

### ISSUE THREAD

**Issue by MacHolgi** [snitzelweck92/homeassistant_alphaess_modbus_tcp#8]
After the AlphaESS update of their infrastructure some days ago the snitzelweck integration works no longer for me. In HA all sensors just state „Entität ist derzeit nicht verfügbar“ (Entity is currently not available).

**Comment by snitzelweck92** [comment]
Hello,

I'm not sure which update you mean.
Because on my system and other systems it is working.
The integration has nothing to do with the infrastructure of the cloud
system of alpha ESS.
It is an local Network Modbus connection.
You have to check the logfiles for details.
Maybe you have updated the Home Assistant?

Can you write details about ur system and homeassistant?
Also the Software Versions?

Thanks

MacHolgi ***@***.***> schrieb am Mo., 6. Nov. 2023, 10:58:

**Comment by MacHolgi** [comment]
Ohh…..I‘m sorry.
I mixed up my Alpha integrations in HA.
Your integration with local modbus tcp information is still working fine.

The problems were coming from this cloud integration: https://github.com/CharlesGillanders/homeassistant-alphaESS

After upgrading on the latest beta, the homeassistant-alphaESS integration is connecting again.

Sorry again for the confusion…
